<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

if( !function_exists('setGrid'))
{
    function setGrid($option=array()){ ?>
        <script type="text/javascript">
            $(function() {
                // $('#listTable').DataTable({
                //     "paging": true,
                //     "lengthChange": true,
                //     "searching": true,
                //     "ordering": true,
                //     "info": true,
                //     "autoWidth": false,
                //     "pageLength": 50,
                //     dom: 'Bfrtip',
                //     'buttons': [
                //         //'copy', 'csv', 'excel', 'pdf', 'print'
                //         'csv', 'excel', 'pdf', 'print'
                //     ]
                // });


                // $(document).on('click', '#ToolTables_listTable_3', function(){
                //     window.print();
                // });

                // $(document).on('click', '.my_print_button', function(){
                //     window.location.href = window.location.href+'&print=true';
                // });
                
                var responsiveHelper_datatable_tabletools = undefined;
                var breakpointDefinition = {
                    tablet : 1024,
                    phone : 480
                };

       //          $('#listTable').dataTable( {
			    //     "sDom": 'T<"clear">lfrtip',
			    //     "oTableTools": {
			    //         "aButtons": [
			    //             {
			    //                 "sExtends": "csv",
			    //                 "sButtonText": "Special columns",
			    //                 "mColumns": [ 0, 1, 4 ]
			    //             },
			    //             {
			    //                 "sExtends": "csv",
			    //                 "sButtonText": "Visible columns",
			    //                 "mColumns": "visible"
			    //             }
			    //         ]
			    //     }
			    // } );

                /* TABLETOOLS */
                var rows_selected = [];
                $('#listTable tr td #list_checkbox').on('click', function(){
                    var rowId = $(this).val();
                    var index = $.inArray(rowId, rows_selected);
                    if(this.checked && index === -1){
                         rows_selected.push(rowId);
                    } else if (!this.checked && index !== -1){
                         rows_selected.splice(index, 1);
                    }
                })

                $('#listTable').dataTable({
                    
                    // Tabletools options: 
                    //   https://datatables.net/extensions/tabletools/button_options
                    "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'T>r>"+
                            "t"+
                            "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
                    "oTableTools": {
                         "aButtons": [
                         //"copy",
                         //"csv",
                         //"xls",
                         	{
                                "sExtends": "csv",
                                "sToolTip": "Save as CSV",
                                //"sTitle": "export_report",
                                /*"sPdfMessage": "Generated by",*/
                                //"sPdfSize": "letter",
                                // "mColumns": [ 0, 1, 5, 4, 6, 7 ]
                            },
                            {
                                "sExtends": "pdf",
                                "sToolTip": "Save as PDF",
                                //"sTitle": "export_report",
                                /*"sPdfMessage": "Generated by",*/
                                "sPdfSize": "letter",
                                // "mColumns": [ 0, 1, 5, 4, 6, 7 ] // these col will be output
                            },
                            // {
                            //     "sExtends": "print",
                            //     /*"sMessage": "Generated by",*/
                            //     "sPdfSize": "letter",
                            //     "mColumns": [ 0, 1, 5, 4, 6, 7 ]
                            // },
                            {
			                    "sExtends": "text",
			                    "sButtonText": "Print",
			                    "sButtonClass": "my_print_button",
			                    "sToolTip": "Click to Print",
			                    "fnClick": function ( nButton, oConfig, oFlash ) {
                                    // var rows_selected = [];
                                    // if ( $('#list_checkbox').length > 0 ){
                                    //     var rows_selected = $('#listTable #list_checkbox:checked').map(function () {
                                    //         return this.value;
                                    //     }).get();

                                    // }
			                        var cur_url = window.location.href;
			                        var query = String(document.location).split('?');
									if (query.length>1)
			                        	cur_url = cur_url+'&print=true';
			                        else
			                        	cur_url = cur_url+'?print=true';

                                    if ( rows_selected.length>0 )
                                        cur_url = cur_url+'&chkIds='+rows_selected;

			                        window.open(cur_url);
			                    }
			                }
                         ],
                        "sSwfPath": "<?php echo base_url();?>/../assets/_back/js/plugin/datatables/swf/copy_csv_xls_pdf.swf"
                    },
                    "lengthChange": true,
                    "autoWidth" : true,
                    "pageLength": 20,
                    'aoColumnDefs': [{
                        'bSortable': false,
                        'aTargets': ['nosort']
                    }],
                    "preDrawCallback" : function() {
                        // Initialize the responsive datatables helper once.
                        if (!responsiveHelper_datatable_tabletools) {
                            responsiveHelper_datatable_tabletools = new ResponsiveDatatablesHelper($('#listTable'), breakpointDefinition);
                        }
                    },
                    "rowCallback" : function(nRow) {
                        responsiveHelper_datatable_tabletools.createExpandIcon(nRow);
                    },
                    "drawCallback" : function(oSettings) {
                        responsiveHelper_datatable_tabletools.respond();
                    }
                });

            });
        </script>
    <?php } ?>
<?php } ?>